apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-admin-binding
  namespace: drone
subjects:
  - kind: ServiceAccount
    name: drone-runner-kube
    namespace: drone
roleRef:
  kind: ClusterRole
  name: drone-admin
  apiGroup: rbac.authorization.k8s.io
