repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

- name: drone
  url: https://charts.drone.io

- name: drone-runner-docker
  url: https://charts.drone.io

- name: drone-runner-kube
  url: https://charts.drone.io

- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
  - name: ingress-nginx
    namespace: ingress-nginx 
    createNamespace: true  
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - Values/Ingress-Nginx/values.yml
  
  - name: drone
    namespace: drone 
    createNamespace: true  
    chart: drone/drone
    version: 0.6.5
    values:
      - Values/Drone/drone-server/values.yaml
  
  - name: drone-runner-kube
    namespace: drone 
    createNamespace: true  
    chart: drone/drone-runner-kube
    version: 0.1.10
    values:
      - Values/Drone/drone-runner-kube/values.yaml

  - name: drone-runner-docker
    namespace: drone 
    createNamespace: true  
    chart: drone/drone-runner-docker
    version: 0.6.2
    values:
      - Values/Drone/drone-runner-docker/values.yaml

  - name: argo
    namespace: argo
    createNamespace: true  
    chart: argo/argo-cd
    version: 7.3.6
    values:
      - Values/Argocd/values.yml